### ISSUE TITLE
DKIM not working (key not valid)

### ISSUE THREAD

**Issue by ronron555** [jeboehm/docker-mailserver#100]
DKIM not working, showing as not valid, the TXT record is matching to the one in the DKIM config page.
![image](https://user-images.githubusercontent.com/45270202/87564279-e1aa1380-c6c8-11ea-8881-423eef6018d8.png)
I checked on the website (https://www.appmaildev.com/en/dkim) and it shows as DKIM: none and I dont know why, other sites like (https://dmarcian.com/dkim-inspector/) are showing it is valid.

if someone can help me it will be appreciated!

**Comment by Itay1787** [comment]
Anyone have any idea how to fix this?

**Comment by jeboehm** [comment]
Just check the difference between these both fields:

<img width="836" alt="Bildschirmfoto 2020-07-19 um 15 19 06" src="https://user-images.githubusercontent.com/3028277/87875738-9c8d2680-c9d3-11ea-925a-a0793a6c758f.png">

**Comment by ronron555** [comment]
> Just check the difference between these both fields:
Thanks for replying!
I checked the two fields several times and they are identical

**Comment by ronron555** [comment]
Hey @jeboehm Just got the DKIM working and it shows as valid in the GUI.
Now the problem is that it isn't actually working, it doesn't show in non of the tests.
I configured SPF and DMARC but DKIM just not working...

**Comment by jeboehm** [comment]
Have you tried disabling and reenabling DKIM in the mailserver-admin panel? This should refresh the configuration.
Personally, I'm using https://email-test.had.dnsops.gov/ to test DKIM.

**Comment by krisnod** [comment]
Hi, I just had a same situation with my DKIM records. It looks like that problem came from space characters in p-value which I had been copy-pasted from DKIM field to my DNS provider's UI.
