### ISSUE TITLE
what is the default password for rspamd or how to define one?

### ISSUE THREAD

**Issue by kklepper** [jeboehm/docker-mailserver#105]
**Is your feature request related to a problem? Please describe.**

Just stumbled at `domain.tld:81/rspamd` and need a password:

![image](https://user-images.githubusercontent.com/6130319/89921916-a256e000-dbfe-11ea-8c20-0cd201cb782e.png)

**Describe the solution you'd like**

Googling and inspecting source code didn't give me a clue what to do here...

**Describe alternatives you've considered**

**Additional context**

Not really critical, just curious; is information about this omitted, and if so, why?

**Comment by jeboehm** [comment]
Hi @kklepper 
see https://github.com/jeboehm/docker-mailserver/wiki/Configuration-variables.
It's the CONTROLLER_PASSWORD environment variable.

**Comment by kklepper** [comment]
Oh, I see, thank you.
