### ISSUE TITLE
Load /webmail by default

### ISSUE THREAD

**Issue by vassad** [jeboehm/docker-mailserver#106]
**Is your feature request related to a problem? Please describe.**
When loading the website, it turns to the login of the mail-admin (/manager location), but common users will need to additionally select the /webmail location instead. Commonly the client application is ran by default on every mail server i've ever seen.

**Describe the solution you'd like**
Edit the web/rootfs/etc/nginx/sites-enabled/10-docker.conf to use the /webmail as default location

**Describe alternatives you've considered**
Add a little snippet for customizing the web/rootfs/etc/nginx/sites-enabled/10-docker.conf and rebuilding the image, or modify the nginx-proxy somehow?

**Additional context**
Tried to do it myself - got able to redirect the default / location to /webmail, but then losing the /manager and unable to get it.
`location / {
return 301 /webmail;
}`

**Comment by jeboehm** [comment]
Hi @vassad 
I've added a link to the webmailer on the manager login page. In addition, users without admin permissions will now see a proper error message.
