### ISSUE TITLE
NGINX Proxy already on my host machine

### ISSUE THREAD

**Issue by TrissieTheHusky** [jeboehm/docker-mailserver#113]
I have Nginx already installed and deployed on my VPS. I’m very confused on how to get it proxied to a domain. I’ve done it before with docker containers but I’m confused cause I have it setup and my ports are exposed. Since you can’t obviously run two Nginx proxies on Port: 80.

**Comment by tiberios1** [comment]
I too have nginx already setup, but in another docker container.  the easiest way is to just make the webhost available on your host on port 81 and just use your existing nginx to proxy to the exposed port. I did find I needed to set the ` VIRTUAL_HOST` environment variable on the web container or the web interface wasn't happy.
