### ISSUE TITLE
Issue deleting aliases

### ISSUE THREAD

**Issue by tiberios1** [jeboehm/docker-mailserver#115]
☺️ Please check the troubleshooting page before opening a new issue. ☺️

https://github.com/jeboehm/docker-mailserver/wiki/Troubleshooting

**Describe the bug**
deleting mail aliases fails

**To Reproduce**
In the Admin area, click on Alias on the left side, then chose an alias to delete and click the delete button next to it.  This should delete the alias.

**Expected behavior**
clicking the delete button returns you to the domain screen without deleting the alias.

**Screenshots**

**Docker environment (please complete the following information):**
 - Output of ```docker info```
 ```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.0-docker)

Server:
 Containers: 24
  Running: 20
  Paused: 0
  Stopped: 4
 Images: 98
 Server Version: 20.10.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-58-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.844GiB
 Name: Virtualbox-20
 ID: I6O7:D4K4:5UAI:62K2:HWQL:GE2B:4PCN:3NL7:6B2P:AUPG:SOZA:RHXX
 Docker Root Dir: /docker/data-root
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
WARNING: No blkio weight support
WARNING: No blkio weight_device support
```

 - Output of ```docker-compose version```
 
```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Additional context**
I have moved the volumes from another server so that may have some impact.  That said I could create new aliases, just not delete them (even new ones I had just created)

**Comment by tiberios1** [comment]
Playing with the admin site some more, it looks like none of the edit or delete actions seem to work, while adding new users / aliases / domains works fine.

**Comment by jeboehm** [comment]
Do you have the admin sites behind a HTTPS proxy configuration? If so, can you check whether your browser tries to send formulars without https?

**Comment by tiberios1** [comment]
Jeffery,

Yes, it's behind an nginx proxy and I'm getting it trying to call the 
page using http rather than https. It's basically the same nginx config 
as I use for a roundcube container.

---
Regards,

Ewan Crowe

On 2021-02-08 15:21, Jeffrey Boehm wrote:

> Do you have the admin sites behind a HTTPS proxy configuration? If so, 
> can you check whether your browser tries to send formulars without 
> https?
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].


Links:
------
[1] 
https://github.com/jeboehm/docker-mailserver/issues/115#issuecomment-775223791
[2]

**Comment by tiberios1** [comment]
I have the following in my nginx config if that helps....

        proxy_set_header        Host $host;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;
        proxy_pass          http://web/;
        proxy_read_timeout  90;
        proxy_redirect      http://web https://<myhostname>/;

**Comment by tiberios1** [comment]
Looks like the delete link is trying to call
```http://<myhostname>/?crudAction=delete&crudId=424772b&entityId=3&menuIndex=0&referrer=http://<myhostname>/?crudAction%3Dindex%26crudId%3D424772b%26menuIndex%3D0%26submenuIndex%3D-1&submenuIndex=-1```

looking at the dev console in chrome, I think it's only using https because Chrome is doing it's thing of redirecting rather than the nginx proxy doing it correctly....

Will go revisit my nginx config again...

**Comment by jeboehm** [comment]
Hi @tiberios1 
I've found the bug! Fixed in #126 

Could you test it again, please?

**Comment by tiberios1** [comment]
Awesome! Thanks, that looks like its resolved the problem.

**Comment by jeboehm** [comment]
Yeah! :)
