### ISSUE TITLE
Outlook 2019 pop3 connection

### ISSUE THREAD

**Issue by zafphire** [jeboehm/docker-mailserver#121]
Hi,
Great job with the mail server.
I am trying without success to connect the mailserver to outlook 2019.
I have tried both POP3 (that i prefer) and IMAP with all of the possible combinations of ports.
Could you please guide me through the appropriate settings for POP3 connection on outlook.
I ve setup the POP3 connection with success in thunderbird already.

Also i would like to ask if there is any easy way to sync the sent mails through webmail, thunderbird and outlook at the same time.

Thank you in advance!

**Comment by agittins** [comment]
> I ve setup the POP3 connection with success in thunderbird already.

This means that you have an outlook problem, rather than a docker-mailserver problem. You might be better off trying an outlook support area instead, but you'll at least need to provide some detail re error messages etc - and which of the 65535 ports you actually tried, and what error(s) you got on each one.

> any easy way to sync the sent mails through webmail, thunderbird and outlook at the same time.

This is exactly what the IMAP protocol is for. The idea is to have all your emails (and their status - read, flagged etc) stored on the server, and each client uses imap to display them. It really is the best way to go for having multiple clients.

**Comment by zafphire** [comment]
Thanks a lot for the quick response,

I just tried once more with the given ports for imap 143 for incoming with starttls and port 25 for outcoming with none/starttls/auto and the error page is the same:
We couldn't connect to the outgoing (SMTP) server. None of the authentication methods supported by Outlook are supported by your server. For more information, contact your email administrator.

**Comment by agittins** [comment]
Ahh. So it sounds like the imap part is probably OK, but the SMTP for sending is having trouble. Lots of ISPs these days block port 25 for clients to reduce the ability for viruses to send spam. Did your thunderbird setup use different SMTP settings, or is it on a different network?

Port 587 is the one to use for SMTP (outgoing), and I think you should be able to enable STARTTLS on it.

**Comment by zafphire** [comment]
To be honest i cannot make it work with outlook. With 587 as port with STARTTLS the message is:
Please check your email address and password and try again.

However with the port 25 for smtp i have succeded to make it work with thunderbird and windows mail too.

I am not able to understand the nature of this error.

It will be very helpful if you find a workaround but if you cant spend more time on that thank you for the support.

**Comment by zafphire** [comment]
Solved!!
Thanks a lot for your help.. Probably it was a rookie mistake.
I followed this post and problem solved:
https://support.kerioconnect.gfi.com/hc/en-us/articles/360015188060--Log-onto-incoming-mail-server-IMAP-failed-When-Setting-up-IMAP-Account-in-Outlook

**Comment by agittins** [comment]
Awesome, glad you got it sorted!
