### ISSUE TITLE
Custom Local Address Extension Character

### ISSUE THREAD

**Issue by svoop** [jeboehm/docker-mailserver#122]
**Is your feature request related to a problem? Please describe.**
I'd like to migrate mailservers which already rely heavily on local address extension using the delimiter `_` (underscore).

Other folks might face the same blocker e.g. when currently using the Postfix-default delimiter `+`.

**Describe the solution you'd like**
A configuration option to set a delimiter different from the default `-` (dash).

This should be relatively easy as it may require no more than two customizations, one in Postfix and the other in Dovecot config files.

**Describe alternatives you've considered**
Migrating the mailservers from the current `_` underscore to the default `-` (dash) is not feasible because addresses using the underscore are in use by hundreds of third-parties.

**Comment by jeboehm** [comment]
Added this feature to master. You can use the new RECIPIENT_DELIMITER environment variable to configure that.

**Comment by svoop** [comment]
@jeboehm Wow, very cool, thanks a lot... and Happy 🐰 🥚

**Comment by jeboehm** [comment]
Happy holidays for you aswell :)
