### ISSUE TITLE
Open relay

### ISSUE THREAD

**Issue by GenesisAdam** [jeboehm/docker-mailserver#134]
Many thanks for this repo. I have spent several hours trying to set up another popular docker mailserver without success. This repo worked first time and the web interfaces are clean and easy to use. Great job.
I tested the email server using an on-line testing site and it flagged this issue of **open relay**:

**I have tried to send out email through the SMTP server and it seemed to accept them. This is a bad thing, as it seems that
your server is an open relay (although I am not sure of this, you must check it!).**

How can I fix this or is it a false flag?

**Comment by jeboehm** [comment]
Hi @GenesisAdam 
I've never experienced such test results.
Which open relay tester are you using?

**Comment by GenesisAdam** [comment]
> 
> 
> Hi @GenesisAdam
> I've never experienced such test results.
> Which open relay tester are you using?

https://mxtoolbox.com/

More Information About Smtp Open Relay

During our diagnostics we attempt to simulate sending a message to a fake email address; test@example.com. We do this to try to detect if your server is an open relay, which means that it accepts mail to domains for which it is not responsible and then passes it along to the proper server. Your server responded with a 200 accepted code to our RCPT TO command. THIS DOES NOT MEAN YOU ARE OPERATING AN OPEN RELAY, only that you may be an open relay.

**Comment by jeboehm** [comment]
I've just used the same tool on my mailserver running in production. There's no open relay. Do you have the example.com addresses still configured? :)
