### ISSUE TITLE
Forward all from a domain to an email.

### ISSUE THREAD

**Issue by storytellar** [jeboehm/docker-mailserver#144]
When I create Alias, the system prevents me to create _star_@domain.com.
The warning of "_star_" is "This value is not valid."
Please show me the solution...
![image](https://user-images.githubusercontent.com/32585529/141611981-6c263d4f-e046-4fff-973c-ca1aa5125d04.png)

**Comment by LuckyCoders** [comment]
+1

**Comment by jeboehm** [comment]
Will be added in the next release! :)
