### ISSUE TITLE
How to enable port SSL port 465

### ISSUE THREAD

**Issue by rover886** [jeboehm/docker-mailserver#146]
Really a great project. 

By following README instructions I could able to up the server.

Everything works really fine, I tested IMAP(S), POP3(S) and Mail Submission as well.

But I have an requirement where I wanted to test an email client with legacy SMTPS protocol instead of using the STARTTLS command", i.e. with port 465. So is it possible to enable SMTP over 465 without STARTTLS command.

**Comment by jeboehm** [comment]
This will be fixed in the next release. You'll have to open that port manually in docker-compose.production.yml (commented for now)
