### ISSUE TITLE
Can't send email to gmail

### ISSUE THREAD

**Issue by manhtien465** [jeboehm/docker-mailserver#227]
i send email test to gmail but i found error in mta is
"Diagnostic-Code: smtp; 550-5.7.1 [113.177.27.200] The IP you're using to send
    mail is not authorized to 550-5.7.1 send email directly to our servers.
    Please use the SMTP relay at your 550-5.7.1 service provider instead. Learn
    more at 550 5.7.1  https://support.google.com/mail/?p=NotAuthorizedError
    bc22-20020a656d96000000b00477ca5b55fcsi12913855pgb.721 - gsmtp"
Content-Description: Undelivered Message
Content-Type: message/rfc822

so how to i send email to gmail

**Comment by jeboehm** [comment]
check your ip at https://mxtoolbox.com/SuperTool.aspx
