### ISSUE TITLE
[Reuqest] Security Headers (CSP) should be added - especially `X-Frame-Options`

### ISSUE THREAD

**Issue by MartinHotmann** [jeboehm/docker-mailserver#230]
All endpoints should be tested against https://securityheaders.com and at least `X-Frame-Options` should be set to prevent malicious visitors' attacks.

All endpoints should be checked:

- /manager/
- /webmail/
- /rspamd/

Thanks in advance!

**Comment by jeboehm** [comment]
Thank you @MartinHotmann!
This will be solved in #241
