### ISSUE TITLE
Catchall addresses

### ISSUE THREAD

**Issue by tiberios1** [jeboehm/docker-mailserver#231]
I see that docker-mailserver supports catchall addresses, I just can't see how these are setup.  What do I need to do to mark a particular address as a catchall for that domain (or even for all domains that are setup)?

**Comment by jeboehm** [comment]
Hi
You need to create a new alias with an empty name field

**Comment by tiberios1** [comment]
@jeboehm That doesn't seem to be possible as the name field is a required field.

**Comment by jeboehm** [comment]
in aliases? not in the latest versions of mailserver-admin

**Comment by tiberios1** [comment]
as far as I know I'm running the latest version. what's the best way to check?
![image](https://user-images.githubusercontent.com/56522082/223966617-8aaa3201-7b01-4735-b7a1-c1b526f689c0.png)

**Comment by jeboehm** [comment]
<img width="1081" alt="Xnapper-2023-03-17-11 44 40" src="https://user-images.githubusercontent.com/3028277/225883631-59b0cc82-8f3d-4a49-be57-394fc6da69ac.png">

This is how the latest version looks like. The mailserver-web image should be at least at version v3.5.0.

**Comment by tiberios1** [comment]
Worked out why I wasn't seeing it.  I'm running a local fork and merged in your main branch then restarted the containers but hadn't rebuilt them.... 🤦

**Comment by jeboehm** [comment]
:D perfect!
