### ISSUE TITLE
Undelivered Mail Returned to Sender

### ISSUE THREAD

**Issue by quangdaik2362001** [jeboehm/docker-mailserver#234]
☺️ Please check the troubleshooting page before opening a new issue. ☺️

https://github.com/jeboehm/docker-mailserver/wiki/Troubleshooting

**Describe the bug**
The IP address sending this message does not have a 550-5.7.25 PTR record setup, or the corresponding forward DNS entry does not 550-5.7.25 point to the sending IP. As a policy, Gmail does not accept messages 550-5.7.25 from IPs with missing PTR records. Please visit 550-5.7.25  https://support.google.com/mail/answer/81126#ip-practices
**To Reproduce**

**Expected behavior**
Send email success 

**Docker environment (please complete the following information):**
 - Output of ```docker info```
 - Output of ```docker-compose version```

**Comment by jeboehm** [comment]
Hi Quang,
your bug description contains the solution.
I'm closing this. Please put more effort into creating a new issue next time.
