### ISSUE TITLE
Option to disable rspamd

### ISSUE THREAD

**Issue by tiberios1** [jeboehm/docker-mailserver#236]
**Is your feature request related to a problem? Please describe.**
I currently pay for an antispam service so I'd like to disable local spam filtering.

**Describe the solution you'd like**
A simple option in the .env file to disable rspamd.

**Describe alternatives you've considered**
N/A

**Additional context**
As an aside, when rspamd is learning ham - does it check all folders or just the inbox?

**Comment by tiberios1** [comment]
I have a simple email that comes from a cronjob that is always flagged as spam despite moving it to another folder each time.  This has been happening for months so it doesn't feel like it is learning, is there a way to check that?  Also where would I be overriding it's configuration if I wanted to do that?

**Comment by jeboehm** [comment]
Could you show me the X-Spamd-Result header of the flagged mails please?

**Comment by tiberios1** [comment]
I've just checked and there is no X-Spamd-Result header, just X-Spam: Yes

**Comment by jeboehm** [comment]
Please check the Rspamd History (in the Rspamd webinterface) when the mail is sent. You can click at the plus sign at every row to get detailed information about the scoring. Please attach that as a screenshot, but be careful not to share sensitive information.

**Comment by tiberios1** [comment]
I managed to fix this by updating the crontab that was running the job to have a MAILFROM line.

**Comment by jeboehm** [comment]
Awesome!
I’ld like to close this. If you need help to override the rspamd scorings, don’t hesitate to open a new issue.
