### ISSUE TITLE
Improvement regarding using command bin/production.sh run --rm web setup.sh

### ISSUE THREAD

**Issue by dheerajayati** [jeboehm/docker-mailserver#266]
**Is your feature request related to a problem? Please describe.**
After firing command bin/production.sh run --rm web setup.sh there will be prompt for creating first or default mail ID and password.
Each time whenever I fire this command I need to manually type for each prompt ( EX:- Please enter the first email address you want to receive mails to: dheeraj@acme.com
Enter a password for the new account: xyz1234
Repeat the password: xyz1234 )

**Describe the solution you'd like**
Is there any possibility of passing mail-id and password with command (Ex:- ./setup.sh email add admin@example.org passwd123)

Please follow below link for your reference.
https://docker-mailserver.github.io/docker-mailserver/v10.1/examples/tutorials/basic-installation/

**Comment by jeboehm** [comment]
Yeah, instead of running setup.sh, you can do

```
bin/production.sh run --rm web /opt/manager/bin/console domain:add example.com
bin/production.sh run --rm web /opt/manager/bin/console user:add --admin --password=changeme --enable admin example.com
```

**Comment by dheerajayati** [comment]
Hii jeboehm,
Thanks for your support
Actually I am facing issue when tried below command

(command fire on vscode bash terminal) bin/production.sh run --rm web /opt/manager/bin/console domain:add acme.com
(Error:-) /usr/local/bin/docker-php-entrypoint: exec: line 9: C:/Program Files/Git/opt/manager/bin/console: not found

(command fire on vscode bash terminal) bin/production.sh run --rm web /opt/manager/bin/console user:add --admin --password=test@1234 --enable admin dheerajayati@acme.com
(Error:-) /usr/local/bin/docker-php-entrypoint: exec: line 9: C:/Program Files/Git/opt/manager/bin/console: not found

**Comment by jeboehm** [comment]
Hi @dheerajayati 
I was wondering if you're using the right project, since you linked to https://docker-mailserver.github.io/docker-mailserver/v10.1/examples/tutorials/basic-installation/ in your initial post yesterday.
This is a different project.  :-) 

If you're doing right, you could try to exec a shell in the web container (`docker exec -it mailserver_web sh`) and run the command beginning from /opt/manager... in there.

**Comment by dheerajayati** [comment]
hi @jeboehm 
Thank you for the guidance
Both domain and add user creation commands are working by using docker exec inside the web container
