### ISSUE TITLE
question: comparison with docker-mailserver/docker-mailserver

### ISSUE THREAD

**Issue by jjangga0214** [jeboehm/docker-mailserver#267]
Hi!

There is [`docker-mailserver/docker-mailserver`](https://github.com/docker-mailserver/docker-mailserver).

I wonder if `jboehm/docker-mailserver` is related to it or totally different project with a naming coincidence.

Thanks :)

**Comment by jeboehm** [comment]
@jjangga0214 totally different :-)

**Comment by jjangga0214** [comment]
Aha!
Thanks for the prompt reply and clarification!
