### ISSUE TITLE
Add 2FA authentication to Roundcube

### ISSUE THREAD

**Issue by cmonty14** [jeboehm/docker-mailserver#272]
**Is your feature request related to a problem? Please describe.**
Authentication in webmailer _Roundcube_ is only user/pw.

**Describe the solution you'd like**
I prefer 2FA for Roundcube.
There's a plugin available: [twofactor_gauthenticator](https://github.com/alexandregz/twofactor_gauthenticator)

**Additional context**
How can I add e.g. _Roundcube_ plugins with this docker architecture?
Could you please advise?

**Comment by jeboehm** [comment]
Hi,

this is documented here: https://github.com/jeboehm/docker-mailserver/wiki/Howto:-Add-Plugins-To-Roundcube-Webmail

I hope this works for you.

**Comment by cmonty14** [comment]
Just to add one more thought to this topic:
It could make sense to install and configure Unbound on host directly, and not in Docker container.
This would follow the recommendation I read about fail2ban.
