### ISSUE TITLE
Customize Container: override of default configuration /etc/<service>.conf

### ISSUE THREAD

**Issue by cmonty14** [jeboehm/docker-mailserver#276]
**Is your feature request related to a problem? Please describe.**
I would like to be able to customize a service by means of overriding default configuration.
Many services provide this function with a _include_ line in services default config, e.g.
`/etc/ssh/sshd_config.d/somefile.conf`
`/etc/sudoers.d/somefile.conf`
`/etc/unbound/unbound.conf.d/somefile.conf`

**Describe the solution you'd like**
To implement this override some services require two changes:

1. Default configuration must be modified with an include directive
2. (Additional) docker volume to store all config files

**Comment by jeboehm** [comment]
Since none of these files is included in any of the images, could you provide some more concrete use cases?

**Comment by cmonty14** [comment]
> Since none of these files is included in any of the images, could you provide some more concrete use cases?

I assumed that you consider to deploy _Unbound_ as recommended by _Rspamd_.

**Comment by jeboehm** [comment]
I'll close this.
Keep in mind that you can mount files or directories anywhere into a container :)
