### ISSUE TITLE
Support for Authentication to relayhost

### ISSUE THREAD

**Issue by tiberios1** [jeboehm/docker-mailserver#316]
**Is your feature request related to a problem? Please describe.**
My relayhost now requires me to pass my username and an app password before relaying my outbound messages.
`5.1.0 Authentication Required (VM401) (in reply to MAIL FROM command)`

**Describe the solution you'd like**
The ability to pass a username and password to the relayhost

**Describe alternatives you've considered**
I could change my relayhost, but I'd prefer not to.

**Additional context**

**Comment by jeboehm** [comment]
Fixed in #204
