### ISSUE TITLE
Unsupported config option 'volumes_from' (docker-compose.yml)

### ISSUE THREAD

**Issue by Harti** [jeboehm/docker-mailserver#46]
I'm currently taking this (awesome!) repository for a test run on my Windows 10 host using Docker for Windows - version 18.03.0-ce-win59 (16762). I think that `docker-compose` is available on 3.6 per default.

Uncommenting the ClamAV extension in the `.env` file and running `docker-compose up [-d]` produces the following error:

```
ERROR: The Compose file '.\docker-compose.yml' is invalid because:
Unsupported config option for services.virus_unof_sig_updater: 'volumes_from'
```

I didn't find anything useful on a quick search on issues around `volumes_from`, and trying to find out more about its proper usage I only really found a [notice in the docker-compose documentation](https://docs.docker.com/compose/compose-file/#volumes) that may or may not have anything to do with it. For the time being, I replaced `volumes_from` with `volumes` - but I have my doubts that this was any useful.

**Comment by jeboehm** [comment]
docker-compose >3 made volumes_from obsolete, because you define the volumes globally and inject them into each service.

I've made the required changes in #48, have a look on it! :)
