### ISSUE TITLE
Intermittent SMTP timeout issues

### ISSUE THREAD

**Issue by Harti** [jeboehm/docker-mailserver#50]
_This repo's SMTP setup has always appeared weird to me. According to the RFC standard, port 25 is only to be used for between-servers exchanging of messages. But 587 is nowhere to be found, it is not being exposed by the containers._

I set up my email clients with outgoing SMTP port being set to 25, and can't seem to send messages reliably. Any test message will take at least a minute to get sent, Outlook tends to time out on that a lot, and it usually requires a retry to finally get it out. The container appears as healthy in `docker ps`. 

Is there any way to debug what I did wrong here?

**Comment by jeboehm** [comment]
Hey @Harti 
I'm working on implementing the submission port 587. But to not introduce a breaking change, I need a configuration toggle for activating this. This needs some time.

A working filter service is required for all smtp actions. So I think this has to do with #49. I'm sure that you can send mails when you have solved that issue.

**Comment by agittins** [comment]
I also ran into this - port 587 is pretty common, especially since a lot of ISPs will block egress on port25 for clients.

I changed my dockerfile override to include:
```
  mta:
    ports:
      - "0.0.0.0:25:25"
      - "0.0.0.0:587:25"
```
and it seems to be working OK on both ports, I can't think of a downside but I'd welcome another perspective...

**Comment by jeboehm** [comment]
Hey agittins
This isn’t a bad solution in any case. I’ld guess that it might be better to do the client smtp communication complete separately from the server communication. For that I’ll try to implement port 587 in a regular way.
I’ll keep you informed.
