### ISSUE TITLE
ssl container startup fails, dkim dmarc

### ISSUE THREAD

**Issue by kzpm** [jeboehm/docker-mailserver#53]
Your docker-mailserver runs nice on my machine.

I have a few questions:

1.  When I issue `docker start` or `docker restart jeboehm/mailserver-ssl:latest` container the startup exits almost immediately.
`docker logs 7ecb6ed322h` shows the following info:
`
Generating a 2048 bit RSA private key
No SSL certificate found. Creating a new one...
........+++
...............................................+++
writing new private key to '/media/tls/mailserver.key'
-----
Signature ok
subject=/C=DE/ST=Northrhine-Westfalia/L=Duesseldorf/O=Mail/OU=Mail/CN=mail.winlin.nl
Getting Private key
SSL certificate was successfully created! Exiting...
SSL certificate found. Exiting...
SSL certificate found. Exiting...
SSL certificate found. Exiting...
SSL certificate found. Exiting...
SSL certificate found. Exiting...
SSL certificate found. Exiting...
`
My question:
How to enable the ssl-container?

2.
Mailing to domains outside the domain I created the mailserver for, fails.
I suppose that it has to do with opendkim, dmarc and spf. 
How can I setup dkim, dmarc and spf in my isp-dns zone?

**Comment by jeboehm** [comment]
Hi kzpm,

the SSL container is designed to run only once when no _official_ certificate exists. So everything is fine here.

In general there should be no problems when you don't have DMARC & stuff set up. The logs of the mta container would help here.
Currently, neither DMARC or OpenDKIM are supported by docker-mailserver.

**Comment by tlappe** [comment]
As far as I understand, rspamd can already sign e-mails with DKIM.

[https://rspamd.com/doc/modules/dkim_signing.html](https://rspamd.com/doc/modules/dkim_signing.html)

[https://workaround.org/ispmail/stretch/prevent-spoofing-dkim/](https://workaround.org/ispmail/stretch/prevent-spoofing-dkim/)

So, is that possible with docker-mailserver? And if so, how and where do I configure it?

**Comment by jeboehm** [comment]
Hi @tlappe ,
currently this is not possible, because the image does not support it.
