### ISSUE TITLE
DKIM

### ISSUE THREAD

**Issue by jeboehm** [jeboehm/docker-mailserver#58]
Relates to #53 

User story
- As a mailserver admin I'ld like to use the webinterface to create DKIM keypairs so that I don't have to use the terminal.
- As a mailserver admin I'ld like the webinterface to guide me regarding the dns records that need to be set.
- As a mailserver admin I want the webinterface to check my domain if I have the dns records properly set up
- As a mail sender I want to have my mails signed automatically with my DKIM keypair, so that the receiver is able to verify the source of that email.

**Comment by aaronchn** [comment]
Hi @jeboehm,

In my opinion, as one of the core functions of the mail server, the strategy about do the dkim and spf or dmarc ... should achieve the most basic functions in the clearest steps based on the minimum components.

If we need a better experience or more dream story in future, we can call that basic function with a higher level tool at a higher level of perspective.

Let me say it directly that Is it possible to consider to create DKIM keypairs or spf? with simple command line interface?

Please forgive my English level, thank you for your code.

FYI: https://github.com/tomav/docker-mailserver/issues/975#issuecomment-415992417 .

**Comment by jeboehm** [comment]
Hey @aaronchn 
DKIM support is now added to the current master branch. It is completely configurable via the management interface. Feel free to try it out!
I appreciate your feedback. :)

**Comment by aaronchn** [comment]
Hi @jeboehm 

To genarate the default DKIM setting for the current domain is a better idea?
With your solution user have to enable Web service If they want to use DKIM feature, this is not they wanted sometimes.

Here is my scrawl that I want to try it in entrypoint.sh with Filter service, but encounter permitted error.

`if ! [ -f /media/dkim/dkim_selectors.map ]`
`then`
    ` chown -R rspamd /media/dkim`
    `chmod 777 /media/dkim`
    `touch /media/dkim/dkim_selectors.map`
    `echo "${DOMAIN} ${CURDATE}" > /media/dkim/dkim_selectors.map`
    `rspamadm dkim_keygen -d ${DOMAIN} -s ${CURDATE} -k /media/dkim/${DOMAIN}.${CURDATE}.key > /media/dkim/${DOMAIN}.${CURDATE}.pub`
    `echo "DKIM public key has been generated:"`
    `cat /media/dkim/${DOMAIN}.${CURDATE}.pub`
`fi`

Honestly, I don't have much skill in this area. If my suggestion is valuable, please consider updating your code. If my suggestion is not feasible, if you are willing , Can you try to guide me how to solve this problem?

Thanks!
