### ISSUE TITLE
Add config for postfix relayhost

### ISSUE THREAD

**Issue by Bonno** [jeboehm/docker-mailserver#63]
Hi,

Is it possible to add a environment setting to configure a relayhost for postfix in the mta image?
I think it will be possible with an extra line ```postconf relayhost="${RELAY_HOST}"``` in mta/rootfs/usr/local/bin/entrypoint.sh

Thanks for the great work.

**Comment by jeboehm** [comment]
Hi @Bonno 

would you like to check branch feature/relayhost? After you have rebuild the images you can set `RELAYHOST` to your `.env` file.

**Comment by Bonno** [comment]
Hi @jeboehm 

The change works perfectly. Thanks for the quick implementation.

**Comment by jeboehm** [comment]
Good to hear that! I have merged the branch. 👍
