### ISSUE TITLE
LDAP support request

### ISSUE THREAD

**Issue by aaronchn** [jeboehm/docker-mailserver#69]
LDAP as a central auth service is a nice architecture in an environment with multiple systems. Fortunately, both POSTFIX and DOVECOT  support LDAP. 

I think your code are best solution I can find about the mail server with dockerize.

Please consider adding new features to support ldap, or make a branch for ldap, and even a project like docker-mailserver-ldap.

BTW: Is it worth considering too that use Mysql and LDAP as multiple authentication backends?

Thanks to this project and contributors!

**Comment by jeboehm** [comment]
Hi @aaronchn 
thank you very much for your feedback.
Adding LDAP support to this project is not (yet) intended. This change would also involve mailserver-admin and the password changing feature in Roundcube. In my opinion this is too much to maintain.
Feel free to do this on your own. If you need help, don't hesitate to ask here! :)

**Comment by aaronchn** [comment]
@jeboehm 
Thank you for your encouragement.
Is it convenient for you to send and receive email? If appropriate, can you send an email (please see my profile ) to ping me when you are free ?

Thanks.

**Comment by jeboehm** [comment]
You've got mail!

**Comment by aaronchn** [comment]
Almost done of LDAP and will try to shere it on Github.
