### ISSUE TITLE
Managing plugins for Roundcube [documentation request]

### ISSUE THREAD

**Issue by agittins** [jeboehm/docker-mailserver#73]
I might have missed some documentation (or just knowledge of docker best practices and how to apply them) but...

What's the best way to add plugins to roundcube with this setup, so that it will survive updates, migrations etc?

I'm particularly interested in things like keyboard shortcuts, contact sync etc, but I expect if there's a "containery way" it would apply to all plugins.

It would be great if this could be mentioned in the docs (or at least, in this thread so as to be discoverable - assuming I didn't simply miss where it's discussed already)! :-)

Thanks for an amazing set-up, you've solved all sorts of headaches for mailserver hosting.

**Comment by jeboehm** [comment]
Hey @agittins 
I like the idea of adding plugins to Roundcube. I've figured out a way to do this by a little change in the docker-compose service definition. Commit 28e73e1 adds documentation and all required changes, BUT there's a little issue in the roundcube/plugin-installer package that breaks the plugin activation routine.
When they hopefully merge my pull request https://github.com/roundcube/plugin-installer/pull/20 I'm going to merge this branch.

**Comment by agittins** [comment]
Sorry for not responding earlier, but this is great stuff, thankyou. I notice they haven't merged your pull request yet, I'm happy to sit tight while they consider it. I wonder if it might be better to add a commandline option to the installer instead, so if it's running under cli it still defaults to "no" unless "-y" or similar is specified on the commandline.

**Comment by agittins** [comment]
Howdy! I notice that the default action change looks like it may have been merged, am I reading that right? Does that make this change practical now or have there been other changes in the meantime that might require more work?

**Comment by jeboehm** [comment]
Hi @agittins,
yeah, you're right. I'm planning to migrate the web container to php8.x and going back to a customized vendor image instead of my one so that the memory footprint lowers.
While doing this I could try fixing this issue.

**Comment by jeboehm** [comment]
Done :)
