### ISSUE TITLE
Allow mailing lists

### ISSUE THREAD

**Issue by tiberios1** [jeboehm/docker-mailserver#80]
**Is your feature request related to a problem? Please describe.**
I'm planning to move to use this project but I currently run a mailing list on my mailserver, so anything sent to the list gets forwarded to a list of addresses.  I use this to let people email one address that gets forwarded to both my wife and me.

**Describe the solution you'd like**
ideally just being able to add multiple addresses when setting up an alias.

**Describe alternatives you've considered**
Mailman, but that seems overly complicated for what I'm looking for

**Additional context**

**Comment by agittins** [comment]
I have exactly the same use-case (well, we're not married, but the email situation's the same!).

You can simply create multiple aliases for the same name, and point them at various addresses. 

This works fine:

```
Name         Destination
foo          bar1@local.domain
foo          bob@external.domain
```
So any email sent to foo@local.domain gets forwarded directly to both bar1@local.domain and bob@external.domain.
