### ISSUE TITLE
MTA bounce email for valid users.

### ISSUE THREAD

**Issue by tiberios1** [jeboehm/docker-mailserver#81]
**Describe the bug**
The MTA is bouncing emails to what should be valid users 
Apr 13 18:49:19 postfix/local[54]: 39FF3448C1: to=<ewan@xxxxxxxx>, relay=local, delay=0.99, delays=0.97/0.01/0/0.01, dsn=5.1.1, status=bounced (unknown user: "ewan")

**To Reproduce**
Create a new environment the initial user via the `bin/production.sh run --rm web setup.sh`. command. Attempt to send an email to the initial user.

**Expected behavior**
User receives email.

**Screenshots**
![image](https://user-images.githubusercontent.com/56522082/79152525-456c2a00-7dc4-11ea-8a7c-a2c239c18830.png)

**Docker environment (please complete the following information):**
 - Output of ```docker info```
Client:
 Debug Mode: false

Server:
 Containers: 8
  Running: 6
  Paused: 0
  Stopped: 2
 Images: 8
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-1063-aws
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 983.7MiB
 Name: ip-172-31-7-67
 ID: RWDD:4JJG:5MTH:YMFG:7CDC:75C3:Q3NM:N5YZ:4TPI:FHDV:DGQJ:JCD3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

 - Output of ```docker-compose version```
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

**Additional context**

**Comment by jeboehm** [comment]
It seems that the configured MAILNAME environment variable is the same as the domain you're trying to receive mails with.
Please configure MAILNAME to something different, eg. **mail.**yourdomain.com.

**Comment by jeboehm** [comment]
Added a note to https://github.com/jeboehm/docker-mailserver/wiki/Configuration-variables
