### ISSUE TITLE
error

### ISSUE THREAD

**Issue by nekojpvn** [jeboehm/docker-mailserver#88]
$ bin/production.sh run --rm web setup.sh
2020/06/01 13:10:05 Waiting for: tcp://web:80
2020/06/01 13:10:05 Waiting for: tcp://db:3306
2020/06/01 13:10:05 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:05 Connected to tcp://db:3306
2020/06/01 13:10:06 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:07 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:08 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:09 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:10 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:11 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:12 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:13 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:15 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:16 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:17 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:18 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:19 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:20 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:21 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:22 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:23 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:24 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:25 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:26 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:27 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:28 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:29 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:30 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:31 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:32 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:33 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:34 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:35 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:36 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:37 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:38 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:39 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:40 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:41 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:42 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:43 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:44 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:45 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:46 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:47 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:48 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:49 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:50 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:51 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:52 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:53 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:54 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:55 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:56 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:57 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:58 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:10:59 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:11:00 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:11:01 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:11:02 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:11:03 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:11:04 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:11:05 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:11:06 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:11:07 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:11:08 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:11:09 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:11:10 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:11:11 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:11:12 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:11:13 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:11:14 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:11:15 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:11:16 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:11:17 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:11:18 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:11:19 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:11:20 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:11:21 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:11:22 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:11:23 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:11:24 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:11:25 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:11:26 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:11:27 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:11:28 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:11:29 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:11:30 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:11:31 Problem with dial: dial tcp 172.19.0.7:80: getsockopt: connection refused. Sleeping 1s
2020/06/01 13:11:32 Connected to tcp://web:80
Welcome to docker-mailserver!
This tool will help you to set up the first mail account.
You just have to answer a few questions.
2020-06-01T13:11:32+00:00 [critical] Uncaught Error: Argument 1 passed to App\Entity\Domain::setName() must be of the type string, null given, called in /opt/manager/src/Command/InitSetupCommand.php on line 71

In Domain.php line 89:

  Argument 1 passed to App\Entity\Domain::setName() must be of the type strin
  g, null given, called in /opt/manager/src/Command/InitSetupCommand.php on l
  ine 71

init:setup [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>

2020/06/01 13:11:32 Command exited with error: exit status 255

**Comment by jeboehm** [comment]
Hi @nekojpvn 
it looks like you don't have a TTY available? This command is an interactive one. If it's not possible for you to use it with a TTY/virtual terminal, then you can add a default login with the command `make fixtures`, or have a look into [the Makefile](https://github.com/jeboehm/docker-mailserver/blob/master/Makefile#L45) how you can create a script for this step.

The default login would be `admin@example.com` with the password `test1234`

**Comment by vassad** [comment]
Hey! Just have recently deployed it successfully several times - and once i had the same issue.
This may mean that containers are not yet ready - check the health status:
```sh
sudo docker container ls --all
```
You should see "Up N minutes (healthy)" or "Up N minutes" on each of the containers.
If not - stop/start with:
```sh
sudo docker container stop <container-id>
sudo docker container start <container-id>
```
Also, the first run after installation may take a huge amount of time generating dhparam of 4096 bits (for me it took 30min+) - after a night i saw it dissapeared in htop, reboot, and saw some containers exited. Restarted everything, waited for 10-15mins and all of them became "Up N minutes (healthy)" and only then i created the admin user.
Hope it helps :)

**Comment by kklepper** [comment]
@vassad Thank you! See last entry in https://github.com/jeboehm/docker-mailserver/issues/85 at `IONOS_1`

**Comment by vassad** [comment]
@kklepper glad you've solved the issue :)
