### ISSUE TITLE
ERROR: The Compose file './docker-compose.yml' is invalid 

### ISSUE THREAD

**Issue by kklepper** [jeboehm/docker-mailserver#93]
**Is your feature request related to a problem? Please describe.**

See
https://github.com/jeboehm/docker-mailserver/wiki/Howto:-Add-Plugins-To-Roundcube-Webmail

> Uncomment the build args section of the web service definition in docker-compose.yml:

- there is no args 

```
root@IONOS_2: /root/docker-mailserver # bin/production.sh build web
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.web: 'args'
```

**Describe the solution you'd like**

Should work as described

**Describe alternatives you've considered**

**Additional context**

**Comment by jeboehm** [comment]
This is what is needed here: https://docs.docker.com/compose/compose-file/#build
I'ld love to see a pull request about this.

**Comment by kklepper** [comment]
Just to let you know: I don't use Webmail in my daily work, so I don't care anymore. 

The service runs flawlessly for months now. Thanks a lot for your good work.

**Comment by jeboehm** [comment]
Thank you! :)
