### ISSUE TITLE
Local address extension -- unprecise

### ISSUE THREAD

**Issue by kklepper** [jeboehm/docker-mailserver#94]
☺️ Please check the troubleshooting page before opening a new issue. ☺️

https://github.com/jeboehm/docker-mailserver/wiki/Troubleshooting

**Describe the bug**

https://github.com/jeboehm/docker-mailserver/wiki/Feature:-Local-Address-Extension

> If you add a - (dash) 

```
Examples:
user1+friends@example.com

user1+1382@example.com
```
- `dash` or `plus` or both?

**To Reproduce**

**Expected behavior**

Please be precise.

**Screenshots**

**Docker environment (please complete the following information):**
 - Output of ```docker info```
 - Output of ```docker-compose version```

**Additional context**

**Comment by jeboehm** [comment]
Good point! I've changed the page, it's a dash.

**Comment by agittins** [comment]
I've added "plus adressing" and "subaddressing" to the text of the wiki page (and now this bug) to make it easier next time I'm trying to find this feature! :-)

**Comment by jeboehm** [comment]
Awesome :)
