### ISSUE TITLE
Please give an example for SPF

### ISSUE THREAD

**Issue by kklepper** [jeboehm/docker-mailserver#96]
**Is your feature request related to a problem? Please describe.**

I know how to set up a `_dmarc` entry because somebody told me. How do you do that with `SPF`?

The service you mention is helpful indeed. I get something like `zzz.tld.  IN TXT "v=spf1 mx a -all"`. So do I insert this like I did with `_dmarc`?

I guess it is a `TXT` entry as well. What is the name of this entry? Is it just `SPF` or is it `_spf` or is it even something else or is it something you just make up a as you like?

You know, all this stuff is not really hard, you just have to know what the correct syntax is. And if you don't, you can spend endless time trying to figure it out.

**Describe the solution you'd like**

If you know, please tell us by example.

**Describe alternatives you've considered**

**Additional context**

**Comment by jeboehm** [comment]
Hi @kklepper 
the text you got from the wizard describes the way how to setup your dns records in a technical but perfect way. I'm not sure how to explain this further. :/

**Comment by kklepper** [comment]
Well, further googling suggested that the `subdomain` field in my nameserver's form should be the FQDN, in this case I chose `mail.zzz.tld`. I hope this is correct.
